name: medication_app_v0
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.2
  dio: ^5.9.0
  easy_localization: ^3.0.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  flutter_barcode_scanner: ^2.0.0
  flutter_mobx: ^2.3.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.0.6
  google_sign_in: ^7.2.0
  http: ^1.6.0
  intl: ^0.19.0
  lottie: ^3.3.1
  mobx: ^2.5.0
  provider: ^6.0.0
  shared_preferences: ^2.0.5
  table_calendar: ^3.1.3
  flutter_local_notifications: ^19.5.0
  flutter_native_timezone: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  mobx_codegen: ^2.7.4


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/lottie/
dependency_overrides:
  file: ^7.0.1
 