name: medication_app_v0
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.2
  dio: ^4.0.0
  easy_localization: ^3.0.0
  firebase_auth: ^1.1.1
  firebase_core: ^1.1.0
  firebase_database: ^6.1.2
  flutter_barcode_scanner: ^2.0.0
  flutter_mobx: ^2.3.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.2
  http: ^0.13.1
  intl: ^0.17.0
  lottie: ^1.0.1
  mobx: ^2.5.0
  provider: 5.0.0
  shared_preferences: ^2.0.5
  table_calendar: ^2.3.0
  flutter_local_notifications: ^5.0.0
  flutter_native_timezone: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  mobx_codegen: ^2.7.4


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - assets/lottie/
 